/**
 * useMealPlan — Fetches the weekly meal plan JSON for the dashboard
 *
 * The meal plan JSON is generated by the scheduled task and served
 * as a static file. This hook fetches it on mount and refreshes
 * every 30 minutes (new plans only drop once a week).
 *
 * Data flow:
 *   Cowork scheduled task → generates markdown → converts to JSON →
 *   placed at /local/mealplan.json on the HA instance (or served
 *   from the Pi's web root) → this hook fetches it.
 *
 * Fallback: If the fetch fails, the hook imports a bundled fallback
 * JSON from src/data/mealplan.json so the widget always has data.
 */

import { useCallback, useEffect, useRef, useState } from 'react';

/* ── Types ── */

export interface MealTopping {
  name: string;
  items: string;
}

export interface Meal {
  type: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  name: string;
  time: string;
  onHand: boolean;
  description: string;
  ingredients: string[];
  steps: string[];
  leftoverNote?: string;
  special?: boolean;
  emoji?: string;
  toppings?: MealTopping[];
}

export interface MealDay {
  date: string;
  label: string;
  note: string;
  meals: Meal[];
}

export interface MealPlan {
  week: string;
  generated: string;
  days: MealDay[];
}

/* ── Helpers ── */

const MEAL_TYPE_ORDER: Record<string, number> = {
  breakfast: 0,
  lunch: 1,
  dinner: 2,
  snack: 3,
};

/** Get the meal type color */
export function mealTypeColor(type: string): string {
  switch (type) {
    case 'breakfast': return '#fbbf24'; // amber
    case 'lunch': return '#4ade80';     // green
    case 'dinner': return '#c4b5fd';    // purple
    default: return '#94a3b8';          // gray
  }
}

/** Get a short label for the meal type */
export function mealTypeLabel(type: string): string {
  switch (type) {
    case 'breakfast': return 'Bfast';
    case 'lunch': return 'Lunch';
    case 'dinner': return 'Dinner';
    case 'snack': return 'Snack';
    default: return type;
  }
}

/** Get today's meals from the plan */
export function getTodayMeals(plan: MealPlan | null): Meal[] {
  if (!plan) return [];
  const now = new Date();
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;

  const today = plan.days.find((d) => d.date === todayStr);
  if (!today) return [];

  return [...today.meals].sort(
    (a, b) => (MEAL_TYPE_ORDER[a.type] ?? 9) - (MEAL_TYPE_ORDER[b.type] ?? 9),
  );
}

/** Get the next upcoming meal (based on time of day) */
export function getNextMeal(plan: MealPlan | null): { meal: Meal; dayLabel: string } | null {
  if (!plan) return null;

  const now = new Date();
  const hour = now.getHours();
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;

  const today = plan.days.find((d) => d.date === todayStr);

  if (today) {
    // Before 10am → show breakfast, 10am-2pm → show lunch, after 2pm → show dinner
    const targetType = hour < 10 ? 'breakfast' : hour < 14 ? 'lunch' : 'dinner';
    const meal = today.meals.find((m) => m.type === targetType);
    if (meal) return { meal, dayLabel: 'Today' };

    // If target type not found, show next available meal
    const remaining = today.meals.filter((m) => {
      const mealOrder = MEAL_TYPE_ORDER[m.type] ?? 9;
      const targetOrder = MEAL_TYPE_ORDER[targetType] ?? 0;
      return mealOrder >= targetOrder;
    });
    if (remaining.length > 0) {
      const sorted = [...remaining].sort(
        (a, b) => (MEAL_TYPE_ORDER[a.type] ?? 9) - (MEAL_TYPE_ORDER[b.type] ?? 9),
      );
      return { meal: sorted[0], dayLabel: 'Today' };
    }
  }

  // If no meals left today, show tomorrow's first meal
  const todayIdx = plan.days.findIndex((d) => d.date === todayStr);
  if (todayIdx >= 0 && todayIdx < plan.days.length - 1) {
    const tomorrow = plan.days[todayIdx + 1];
    const sorted = [...tomorrow.meals].sort(
      (a, b) => (MEAL_TYPE_ORDER[a.type] ?? 9) - (MEAL_TYPE_ORDER[b.type] ?? 9),
    );
    if (sorted.length > 0) return { meal: sorted[0], dayLabel: tomorrow.label };
  }

  // Fallback — show first meal of the plan
  for (const day of plan.days) {
    if (day.meals.length > 0) {
      return { meal: day.meals[0], dayLabel: day.label };
    }
  }

  return null;
}

/** Format a day label for display — "Fri 3/27" */
export function formatDayShort(day: MealDay): string {
  const abbr = day.label.slice(0, 3);
  const parts = day.date.split('-');
  if (parts.length === 3) {
    return `${abbr} ${parseInt(parts[1])}/${parseInt(parts[2])}`;
  }
  return abbr;
}

/* ── Hook ── */

// Try HA local path first, then fall back to bundled data
const MEALPLAN_URL = '/local/mealplan.json';

export function useMealPlan() {
  const [plan, setPlan] = useState<MealPlan | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const fetchPlan = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      // Try fetching from HA local files first
      const resp = await fetch(MEALPLAN_URL);
      if (resp.ok) {
        const data: MealPlan = await resp.json();
        setPlan(data);
        setLoading(false);
        return;
      }
    } catch {
      // Network error — fall through to bundled fallback
    }

    try {
      // Fallback: import bundled JSON
      const mod = await import('@/data/mealplan.json');
      setPlan(mod.default as unknown as MealPlan);
    } catch (err) {
      console.error('[Home OS] Meal plan fetch error:', err);
      setError('Failed to load meal plan');
    } finally {
      setLoading(false);
    }
  }, []);

  // Fetch on mount and every 30 minutes
  useEffect(() => {
    fetchPlan();
    intervalRef.current = setInterval(fetchPlan, 30 * 60 * 1000);
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [fetchPlan]);

  return { plan, loading, error, refresh: fetchPlan };
}
